### ISSUE TITLE
Header or footer not showing up.

### ISSUE THREAD

**Issue by jhunexjun** [codedge/laravel-fpdf#11]
I have this in web routes
`Route::get('/fpdf', 'myController@method');`
Then inside myController
```php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Fpdf;

class PDF extends Fpdf {
    function Header() {
    	$this->Image(storage_path() . 'logo.png',10,6,30);
    	$this->SetFont('Arial','B',15);
    	$this->Cell(80);
    	$this->Cell(30,10,'Title',1,0,'C');
    	$this->Ln(20);
    }
    function Footer() {
    	$this->SetY(-15);
    	$this->SetFont('Arial','I',8);
    	$this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
    }
}

class myController extends Controller {
    public function method() {
    	$pdf = new PDF();
    	$pdf::AliasNbPages();
    	$pdf::AddPage();
    	$pdf::SetFont('Times','',12);

    	for($i=1;$i<=40;$i++)
    	    $pdf::Cell(0,10,'Printing line number '.$i,0,1);

	    $pdf::Output();
	    exit;
    }
}
```
The header and footer are not showing up only the main section. I don't see any errors.
Thanks.

**Comment by codedge** [comment]
I'll have a look later this evening. 

Just to clarify:
- Your `PDF` class and your controller are in one single file?
- Why are you having an `exit` statement at the end of your `method` method?
- Why don't you use either Facades or proper dependency injection? 

I think is sth. mixed up in your code. Nobody else is having this problem.

**Comment by codedge** [comment]
As I supposed, not a problem with the package, but with your code.
Here is some help to fix!

Insert into `routes/web.php`:
```php
Route::get('/fpdf', 'Controller@createPdf');
```

Create a model in `app/Models/Pdf.php` that extends the `Pdf` model from the package and override the `Header` and `Footer` method and __do not__ do this in your controller file:

```php
<?php

namespace App\Models;

use Codedge\Fpdf\Fpdf\Fpdf;

class Pdf extends Fpdf
{
    public function Header()
    {
        $this->Image(storage_path() . '/logo.jpg',10,6,30);
        $this->SetFont('Arial','B',15);
        $this->Cell(80);
        $this->Cell(30,10,'Title',1,0,'C');
        $this->Ln(20);
    }

    public function Footer()
    {
        $this->SetY(-15);
        $this->SetFont('Arial','I',8);
        $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
    }
}
```

In your controller, i. e. `app/Http/Controllers/Controller.php` you need to inject the `Pdf` model in the constructor like this:

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    protected $pdf;

    public function __construct(\App\Models\Pdf $pdf)
    {
        $this->pdf = $pdf;
    }

    public function createPdf()
    {
        $this->pdf->AliasNbPages();
        $this->pdf->AddPage();
        $this->pdf->SetFont('Times','',12);

        for($i=1;$i<=40;$i++)
            $this->pdf->Cell(0,10,'Printing line number '.$i,0,1);

        $this->pdf->Output();
    }
}

```

The result is (with a different logo of course):
<img width="1033" alt="2017-06-02_22-56-23" src="https://cloud.githubusercontent.com/assets/4409904/26744578/ccc74f1e-47e6-11e7-8ed9-e640cd7490cd.png">

**Comment by jhunexjun** [comment]
Hi,

I just want to answer your questions above.

- Your PDF class and your controller are in one single file?
    Yes. Where it should be placed? I don't see it in some examples. Am I missing?
- Why are you having an exit statement at the end of your method method?
    If there's no exit, it doesn't show as pdf in Chrome but full of unkown characters like %PDF-1.3 3 0 obj <> endobj 4 0 obj <> stream x�}. I noticed the content-type is not application/pdf but text/html; charset=UTF-8. It shows correctly though in Internet Explorer.
- Why don't you use either Facades or proper dependency injection?
I don't see it in docs.

Thanks,
