### ISSUE TITLE
Digital data is gone missing when trying to update the pdf. 

### ISSUE THREAD

**Issue by euginepj** [codedge/laravel-fpdf#136]
I am trying to add an image to the pdf which have some digital data in it. (Some field are filled from "Zoho Sign", "Docusign"). 
I am able to generate the pdf with that image in it. But the digital data is gone missing. 

Is there are any way to get the digital data with the pdf? 
Please help me to sort this problem. 

The Code, I used, is shown below: 
`
use setasign\Fpdi\Fpdi;

$pdf = new FPDI();
$pdf->setSourceFile('uploads/document_name.pdf');
$pagecount  = $pdf->setSourceFile('uploads/document_name.pdf');

for ($i = 0; $i < $pagecount; $i++) {

   // Adding the Pages 
   $pdf->AddPage(); 

   $tpl = $pdf->importPage($i + 1, '/MediaBox', true);
   $pdf->useTemplate($tpl, 0, 0, 208);
   $pdf->Rect(0, 0, 210, 295, 'D');

   $pdf->Image($image, 90, 170, -450);
 }

$pdf->Output('D'); 
`

**Comment by erikn69** [comment]
Did you try asking at [Setasign/FPDI](https://github.com/Setasign/FPDI/issues)?

There is no posible to add data with FPDI without losing data like signatures, FPDI only creates a copy page to page, it don't add new data to a existing pdf

Also this is a fpdf wrapper, the real libray is on http://www.fpdf.org/
