### ISSUE TITLE
Support Laravel 9

### ISSUE THREAD

**Issue by wbetalleluzd** [codedge/laravel-fpdf#139]
wbeta@Laptop-WRBD MINGW64 /d/Projects Laravel - Livewire/Projects/idept.edu.pe - IDEPT System
$ composer require codedge/laravel-fpdf
Using version ^1.8 for codedge/laravel-fpdf
./composer.json has been updated
Running composer update codedge/laravel-fpdf
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires codedge/laravel-fpdf ^1.8 -> satisfiable by codedge/laravel-fpdf[1.8.0].
    - codedge/laravel-fpdf 1.8.0 requires illuminate/support ^6.0 || ^7.0 || ^8.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require codedge/laravel-fpdf:*" to figure out if any version is installable, or "composer require codedge/laravel-fpdf:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by philipe-vieira** [comment]
I'm going through the same problem. 
I need to update a project to laravel 9.0 asap. :(

**Comment by codedge** [comment]
[Release 1.8.5](https://github.com/codedge/laravel-fpdf/releases/tag/1.8.5) support Laravel 9
