### ISSUE TITLE
Add scripts

### ISSUE THREAD

**Issue by gilyon-1** [codedge/laravel-fpdf#146]
How can I add scripts. 
I have added them to the /vendor/codedge/laravel-fpdf/src/Fpdf folder.
e.g.: code128.php [http://www.fpdf.org/en/script/script88.php](url)
In my controller instead of 
`use Codedge\Fpdf\Fpdf\Fpdf;`  ---> `use Codedge\Fpdf\Fpdf\Code128;`
`$pdf = new PDF_Code128('L','mm',array(120,114));`

What am I missing to implement this?

**Comment by codedge** [comment]
There is no possibility add additional scripts. Use it as it is - or propose a new feature and create a MR.
