### ISSUE TITLE
PHP 8.1 DEPRECATED warning

### ISSUE THREAD

**Issue by ormelflores** [codedge/laravel-fpdf#159]
warning persist when generating pdf file
<img width="1397" alt="Screen Shot 2022-04-28 at 4 57 47 PM" src="https://user-images.githubusercontent.com/60385109/165716927-ea3d9e9d-89b3-4ff0-8ea7-a8080cd1dbb8.png">

**Comment by codedge** [comment]
This is a problem with FPDF itself (http://www.fpdf.org/phorum/read.php?f=1&i=62067&t=62067) and not with this wrapper here.

It will still work, just the deprecation message is going to appear.

**Comment by ormelflores** [comment]
hmm okay, guess I'll wait for it to be fixed. It will work, but it's affecting speed performance when generating a pdf. anyway, thanks
