### ISSUE TITLE
Laravel change font path

### ISSUE THREAD

**Issue by keradach** [codedge/laravel-fpdf#163]
how to change font path other

**Comment by poncianodiego** [comment]
Just define the constant on your AppServiceProvider or somewhere before the singleton is instantiated. I created a [PR](https://github.com/codedge/laravel-fpdf/pull/165/files) addressing this.

**Comment by codedge** [comment]
I don't get why you need to override the extended methods? 

A smaller PR with just setting the FPDF_FONTPATH before the the singleton is instantiated would be enough, I guess.

**Comment by codedge** [comment]
I added the possibility to change the font path. Please [see this section](https://github.com/codedge/laravel-fpdf#defining-fonts) in the readme.
