### ISSUE TITLE
How to use in a controller?

### ISSUE THREAD

**Issue by BenjaminHoegh** [codedge/laravel-fpdf#18]
How to use in a controller?

Laravel 5.6

**Comment by barisbora** [comment]
For example POST Method in your controller, Laravel auto resolver create instance for you. Also u can statically call class

```
public function store(Request $request, Codedge\Fpdf\Fpdf\Fpdf $fpdf) {

    $fpdf->AddPage();
    $fpdf->SetFont('Courier', 'B', 18);
    $fpdf->Cell(50, 25, 'Hello World!');
    $fpdf->Output();

});
```

**Comment by sbarbosa115** [comment]
This code works for my using Laravel 5.6 and codedge/laravel-fpdf 1.2

`public function print(): BinaryFileResponse
    {
        Fpdf::AddPage();
        Fpdf::SetFont('Courier', 'B', 18);
        Fpdf::Cell(50, 25, 'Hello World!');
        Fpdf::Output('F', $pathFile);
        $headers = ['Content-Type' => 'application/pdf'];
        return response()->file($pathFile, $headers);
    }`

Do not forget to import FPDF facade.

`use Codedge\Fpdf\Facades\Fpdf;`
