### ISSUE TITLE
NEW WAY TO WORK

### ISSUE THREAD

**Issue by kardoqadir** [codedge/laravel-fpdf#21]
I have used your code it did not work.. Anyhow we should pass it through response 
```
Fpdf::AddPage();
Fpdf::SetFont('Courier', 'B', 18);
Fpdf::Cell(50, 25, 'Hello World!');
// Fpdf::Output();
return response(Fpdf::Output(), 200)->header('Content-Type', 'application/pdf');
```

**Comment by codedge** [comment]
You can see a working example in the https://github.com/codedge/laravel-fpdf/blob/master/README.md - which is already mentioned by @rubelkolpolok
