### ISSUE TITLE
easyTable 

### ISSUE THREAD

**Issue by stepgr** [codedge/laravel-fpdf#239]
Hi ,

switching an app from Codeigniter 3 to Laravel  and  stuck on using this library :   
fpdf-easytable/fpdf-easytable 

Any way to use this library on this package ?  In CI  it was pretty easy to implement 
but here with composer I'm kinda lost  and haven't figured out which way to go yet. 
Do I need to edit FpdfServiceProvider.php for this or  there is some other way to use it ?

Thanks.

**Comment by yudistirasd** [comment]
i've used fpdf-easytable package for several laravel project, my implementation is : 
1. extract fpdf-easy-table to App\Libraries\EasyTable or any folder you want
2. Modify formatedstring.php
`
<?php
namespace App\Libraries\EasyTable;

class FormatedString{ 
}
`
4. Modify exFPDF.php
`<?php
 namespace App\Libraries\EasyTable;

 use App\Libraries\EasyTable\FormatedString;
 use Codedge\Fpdf\Fpdf\Fpdf;

 class exFPDF extends FPDF {`
6. Modify easyTable.php 
`<?php

namespace App\Libraries\EasyTable;

class easyTable{`

and this an example to create pdf with fpdf-easytable
`<?php

namespace App\Cetak;

use App\Libraries\EasyTable\exFPDF;
use App\Libraries\EasyTable\easyTable;

trait NotaKeluar
{
    public function cetak()
    {
        $pdf = new exFPDF();

        $pdf->addPage('P', "A4");

        $pdf->setFont('Arial', 'B', 8);

        $table = new easyTable($pdf, '{40, 60, 40, 60}', 'l-margin:3.5; width:100%;border:1;');
        $table->easyCell("test", "colspan:2;border:0");
        $table->printRow();
        $table->endTable(-0.1);
        $pdf->output('I', 'test');

        exit;
    }
}
`

**Comment by stepgr** [comment]
Thank you ,

in the meantime I ended up using dompdf with an html table , pretty much the same outcome (not 100%  but acceptable) . I will keep this for future reference anyway .
