### ISSUE TITLE
Problems with the headers.

### ISSUE THREAD

**Issue by NicoxDJ** [codedge/laravel-fpdf#24]
Hello!
This script doesn't really work correctly on Laravel 5.5

When i did everything and try to test it, it doesn't actually create the pdf headers.
From the "Hello World" demo, the only thing that i see is this:

> %PDF-1.3 3 0 obj <> endobj 4 0 obj <> stream x�3R��2�35W(�r Q�w3T0��30PISp 	�Z*���*��(hx����+���(j*�d���Q endstream endobj 1 0 obj <> endobj 5 0 obj <> stream x�]R�n�0��>��L�%�DI�8���~�%E*r�ﻻvҪHX�gvVk?/���Ῑ��`]�[�x5 �3\z��P�}����PO���j�Jݍ^���x6/f�����������|���4}�z�����}���@�,ۖ-��˺E�u�^�,���<� �Z_�K� IQ����Yd����C�K�_�%q�8>�!J"V!2&bGģ%r"H��D��\}2EL1n��h�j���e��"a*H����:��d��9c���[�X1~��"�3�g��Ñ�;O��> endobj 2 0 obj << /ProcSet [/PDF /Text /ImageB /ImageC /ImageI] /Font << /F1 6 0 R >> /XObject << >> >> endobj 7 0 obj << /Producer (FPDF 1.81) /CreationDate (D:20180904171808) >> endobj 8 0 obj << /Type /Catalog /Pages 1 0 R >> endobj xref 0 9 0000000000 65535 f 0000000230 00000 n 0000000867 00000 n 0000000009 00000 n 0000000087 00000 n 0000000317 00000 n 0000000751 00000 n 0000000971 00000 n 0000001047 00000 n trailer << /Size 9 /Root 8 0 R /Info 7 0 R >> startxref 1096 %%EOF

So what i have to change, to work correctly?

**Comment by Bigking237** [comment]
Hello man! 
Just add `exit;` at the end of your code .. for example : 
`$fpdf = new Fpdf;
 $fpdf->AddPage();
 $fpdf->SetFont('Courier', 'B', 18);
 $fpdf->Cell(50, 25, 'Hello World!');
 $fpdf->Output();
 exit;`

**Comment by robie69** [comment]
I'm running 5.4. When you move this to a controller(which I assume you probably will), you can use

`return response($fpdf->Output(), 200)->header('Content-Type', 'application/pdf');`
