### ISSUE TITLE
Error: Exception Class Not Found in src/Fpdf/Fpdf.php

### ISSUE THREAD

**Issue by oscar-ol** [codedge/laravel-fpdf#244]
When the Error method in src/Fpdf/Fpdf.php is executed, it cannot find the Exception class and returns the error: "Class "Codedge\Fpdf\Fpdf\Exception" not found".

I created a PR that solved it. #241

**Comment by codedge** [comment]
Fixed with https://github.com/codedge/laravel-fpdf/pull/241
