### ISSUE TITLE
How to extend FPDF class

### ISSUE THREAD

**Issue by itsmoto** [codedge/laravel-fpdf#25]
I want to extend FPDF class so that I can override functions(header & footer).

code
`class PDF extends FPDF
{
function Header()
{
    global $title;

    // Arial bold 15
    $this->SetFont('Arial','B',15);
    // Calculate width of title and position
    $w = $this->GetStringWidth($title)+6;
    $this->SetX((210-$w)/2);
    // Colors of frame, background and text
    $this->SetDrawColor(0,80,180);
    $this->SetFillColor(230,230,0);
    $this->SetTextColor(220,50,50);
    // Thickness of frame (1 mm)
    $this->SetLineWidth(1);
    // Title
    $this->Cell($w,9,$title,1,1,'C',true);
    // Line break
    $this->Ln(10);
}

function Footer()
{
    // Position at 1.5 cm from bottom
    $this->SetY(-15);
    // Arial italic 8
    $this->SetFont('Arial','I',8);
    // Text color in gray
    $this->SetTextColor(128);
    // Page number
    $this->Cell(0,10,'Page '.$this->PageNo(),0,0,'C');
}}`

**Comment by robie69** [comment]
This has been answered (kindof) in issue #11 
I use this to add additional functionality (textboxes, barcodes) to the class, but it's only useful for headers and footers if they don't change, unless I'm missing something, which is possible. 

https://github.com/codedge/laravel-fpdf/issues/11
