### ISSUE TITLE
Compatibility Laravel 11

### ISSUE THREAD

**Issue by wbetalleluzd** [codedge/laravel-fpdf#280]
OMG I am waiting a week or more to update to Laravel 11 and I cant because I need this package....
I think we move to Dompdf.
Im sorry, but you dont update yet.

**Comment by markcanals** [comment]
Does anyone know if this package will be updated to be used with Laravel 11?

**Comment by jeroen-hso** [comment]
Composer.json in master branch is updated to support Laravel 11.

The following workaround works for me:
composer.json
```
"require": {
   "codedge/laravel-fpdf": "dev-master",
}
"repositories": [
        {
          "type": "vcs",
          "url": "https://github.com/codedge/laravel-fpdf.git"
        }
      ]
```

**Comment by Mrkars** [comment]
Thank you Jeroen-hso!

**Comment by codedge** [comment]
i think there was just a release missing. I created the 1.12.1 release which support now L 11.
