### ISSUE TITLE
Decoding?

### ISSUE THREAD

**Issue by sanalbakis** [codedge/laravel-fpdf#3]
Hi,
I have just installed the fpdf, and when I output 'hello world' example, I get a text that is not decoded. 

![fpdf](https://cloud.githubusercontent.com/assets/890838/20343657/84a528e8-abef-11e6-963d-8011812276ce.png)

**Comment by sanalbakis** [comment]
I had to write "exit;" at the end. The problem was solved.

**Comment by huchenhai** [comment]
thank you
