### ISSUE TITLE
Missing exit; in the sample code

### ISSUE THREAD

**Issue by castorland** [codedge/laravel-fpdf#30]
Hi there!
Great work thanks! I just want to tell you, that it works for me only if I put an exit; after the code. I am using Laravel 5.8. So the final code is:
$pdf = new FPDF('P','mm','A4');
$pdf->AddPage();
$pdf->SetFont('Arial','B',16);
$pdf->Cell(40,10,'Hello World!');
$pdf->Output();
exit;

**Comment by garytron** [comment]
Thank you! I had the same issue! :P

**Comment by Thowo91** [comment]
I think you had the same error as here
[https://stackoverflow.com/questions/14359914/fpdf-generated-pdf-is-not-displayed-properly-in-browser](url)

`ob_get_clear();`
Before the $pdf->Output(); should also help for the browser view
