### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by pranser** [codedge/laravel-fpdf#44]
[Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 16:
  ...^1.5",            },    "require-dev"
  --------------------^
  Expected: 'STRING' - It appears you have an extra trailing comma

**Comment by codedge** [comment]
The problem is not in this package, as I do not have any `Seld\JsonLint` in my `package.json`.
Furthermore you can see [here](https://github.com/codedge/laravel-fpdf/actions) that the package installs fine.
