### ISSUE TITLE
> endobj 2 0 obj

### ISSUE THREAD

**Issue by facualba-suricata** [codedge/laravel-fpdf#47]
Hi i need help with this error

![image](https://user-images.githubusercontent.com/67796887/90173068-3ef1bd00-dd7a-11ea-943a-29e83cca1fa8.png)

In my controller i have this

![image](https://user-images.githubusercontent.com/67796887/90173132-5c268b80-dd7a-11ea-9c26-82c1f88cbe48.png)

I hope prompt help. Regards

**Comment by codedge** [comment]
Put an `exit;` at the end or download the PDF file.
