### ISSUE TITLE
problem during installation

### ISSUE THREAD

**Issue by DiegoSF1996** [codedge/laravel-fpdf#49]
Hello, how are you? first of all thanks for this dependency.
I'm having this problem with the installation:

C:\xampp\htdocs\SIA - Copia>composer require codedge/laravel-fpdf
Using version ^1.7 for codedge/laravel-fpdf
./composer.json has been updated
Running composer update codedge/laravel-fpdf
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires codedge/laravel-fpdf ^1.7 -> satisfiable by codedge/laravel-fpdf[1.7.0].
    - codedge/laravel-fpdf 1.7.0 requires illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by codedge** [comment]
Hey,

what version of Laravel do you use? Is that the complete output you get?

**Comment by DiegoSF1996** [comment]
my version is 5.8.
yes, that's all that came back to me.
![image](https://user-images.githubusercontent.com/48593328/97715218-e68caa80-1aa0-11eb-89c2-ff025807bf2e.png)

**Comment by codedge** [comment]
This package only support Laravel 6.x, 7.x and 8.x. Laravel 5 is not supported by this package, and generally not supported anymore by the Laravel team - see [supported versions](https://laravel.com/docs/8.x/releases#support-policy).

**Comment by DiegoSF1996** [comment]
thank you brother
