### ISSUE TITLE
Encode character UTF8

### ISSUE THREAD

**Issue by antoine1003** [codedge/laravel-fpdf#64]
Hi guys,

I installed this package for my website, pdf exported will contains the name of the logged users. All french accents are correctly encoded with `utf8_decode` function but some czech accents are not correctly encoded as the name  'Vojtěch' .

Is there any way to do it ? I wanted to change font with custom one but it doesn't seems possible.

Thanks,
Antoine

**Comment by codedge** [comment]
Unfortunately I cannot answer this. This package here just provides the [FPDF](http://www.fpdf.org/) as is. There is no special handling inside this package here, just a convienient way to use FPDF with Laravel.

**Comment by antoine1003** [comment]
Okay, well thank you for your answer
