### ISSUE TITLE
 Unsupported operand types: string / float 

### ISSUE THREAD

**Issue by SamuelMwangiW** [codedge/laravel-fpdf#65]
I am getting the subject error from the following line https://github.com/codedge/laravel-fpdf/blob/ca825a75eecfab9e1e348d7643e4d46630b4d3c9/src/Fpdf/Fpdf.php#L516
The error is obviously in Fpdf and the solution would be to covert size to int first before performing the operation e.g but are wondering if the PR should be raised here or upstream.
```PHP
$this->FontSize = intval($size)/$this->k;
```

**Comment by codedge** [comment]
As this is clearly an FPDF error, the issue should be raised upstream. This package `laravel-fpdf` just provideds a convenient way to include the FPDF lib, but does not improve it or fix errors in it.
