### ISSUE TITLE
Installation and README clarification

### ISSUE THREAD

**Issue by hotsaucejake** [codedge/laravel-fpdf#7]
In order to publish the config file:
````
php artisan vendor:publish --provider="Codedge\Fpdf\FpdfServiceProvider" --tag=config
````
you must first register the service provider.  In your installation procedures you list the above command to run after the ````composer require```` command.  

For future users you should simply add registering the service provider instructions before the config command in your README.

**Comment by codedge** [comment]
Hi @hotsaucejake,
your're totally right - the instructions are a bit confusing. I updated the README.md file to make it more clear.

Thanks for the hint.

**Comment by exeleon** [comment]
3 years later and this issue helped me... Why the README doesn't specify this?
