### ISSUE TITLE
Non-static methods should not be called from a static context

### ISSUE THREAD

**Issue by hotsaucejake** [codedge/laravel-fpdf#8]
Was getting an error when I was trying to access it statically:

````php
Fpdf::AddPage();
````

I fixed it by [changing this line](https://github.com/codedge/laravel-fpdf/blob/master/src/FpdfServiceProvider.php#L48) from
````php
return new Fpdf\FPDF(
````
to
````php
return new Fpdf\Fpdf(
````

**Comment by codedge** [comment]
Thanks for the hint @hotsaucejake. Already fixed!
